FROM node:alpine
WORKDIR /frontend
COPY . .
RUN npm install && \ 
    npm run build && \
    npm install -g serve && \ 
    adduser -D appuser
USER appuser
CMD [ "serve", "-s", "-l", "5000", "build" ]
