# Generated by Django 3.1.2 on 2021-02-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210217_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
