# Generated by Django 3.1.2 on 2021-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_ambulance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pc', 'Personal Care'), ('f', 'Family Care'), ('fs', 'Fitness and Suppliments'), ('p', 'Pharmacy')], max_length=24),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
