# Generated by Django 3.1.2 on 2021-03-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210302_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phonenumber',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
