# Generated by Django 3.1.2 on 2021-03-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210306_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='research_journals',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='study',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
