# Generated by Django 3.1.2 on 2021-03-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210306_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocotorAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=6)),
                ('descriptions', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
