# Generated by Django 3.1.2 on 2021-03-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_docotorappointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocotorAppointment',
            new_name='DoctorAppointment',
        ),
    ]
