# Generated by Django 3.1.2 on 2021-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210306_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Personal Care', 'pc'), ('Family Care', 'f'), ('Fitness and Suppliments', 'fs'), ('Pharmacy', 'p')], max_length=24),
        ),
    ]
