# Generated by Django 3.1.2 on 2021-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prescribedmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
