# Generated by Django 3.1.2 on 2021-02-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product_prescribedmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='provinence',
            new_name='Province',
        ),
    ]
