# Generated by Django 3.1.2 on 2021-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210217_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='Province',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
