# Generated by Django 3.1.2 on 2021-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210305_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facebook',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='websitelink',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
