# Generated by Django 3.1.2 on 2021-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210308_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Personal Care', 'Personal Care'), ('Family Care', 'Family Care'), ('Fitness and Suppliments', 'Fitness and Suppliments'), ('Pharmacy', 'Pharmacy')], max_length=24),
        ),
    ]
