version: "3"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  frontend:
    image: bigyank/docker-frontend
    build: ./frontend
    ports:
      - 3000:5000

  backend:
    image: bigyank/docker-backend
    build: ./backend
    ports:
      - 4000:8080
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  redis:
    image: redis
