version: "3"
services:
  frontend:
    image: bigyank/docker-frontend
    build: ./frontend
    ports:
      - 3000:5000

  backend:
    image: bigyank/docker-backend
    build: ./backend
    ports:
      - 4000:8080

  redis:
    image: redis
    ports:
      - 6370:6379
