version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresdata:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - ./redis:/data

  frontend:
    image: bigyank/docker-frontend
    build: ./frontend
    depends_on:
      - backend

  backend:
    image: bigyank/docker-backend
    build: ./backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

